name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 * * * *"  # Runs hourly
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Update README
        uses: leetcode-action/update-readme@latest
        with:
          username: "Udhayan_sk7"
          readme-path: "README.md"
